# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.resize(361, 586)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setStyleSheet("background-color:rgb(35, 0, 17);")
        Dialog.setWindowIcon(QIcon('assets/siri.gif'))
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 251, 61))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(240, 240, 240);")
        self.label_4.setWordWrap(True)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 310, 311, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(240, 240, 240);")
        self.label_3.setWordWrap(True)
        self.verticalLayout_2.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(240, 240, 240);")
        self.label.setWordWrap(True)
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(240, 240, 240);")
        self.label_2.setWordWrap(True)
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(240, 240, 240);")
        self.label_5.setWordWrap(True)
        self.verticalLayout_2.addWidget(self.label_5)
        self.voiceFig = QtWidgets.QPushButton(Dialog)
        self.voiceFig.setGeometry(QtCore.QRect(140, 120, 90, 90))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/siri.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voiceFig.setIcon(icon)
        self.voiceFig.setIconSize(QtCore.QSize(220, 220))
        self.voiceFig.setObjectName("voiceFig")
        self.movie = QtGui.QMovie("assets/siri-ianzhao.gif")
        self.movie.frameChanged.connect(lambda: self.voiceFig.setIcon(
            QtGui.QIcon(self.movie.currentPixmap())))
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 281, 41))
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(240, 240, 240);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "语音助手小思"))
        self.label_4.setText(_translate("Dialog", "你好！小思能帮到你吗？"))
        self.label_3.setText(_translate("Dialog", "你可以点击图标试着说："))
        self.label.setText(_translate("Dialog", "1.\"来点音乐\"来听音乐"))
        self.label_2.setText(_translate("Dialog", "2. \"打开记事本\"来打开笔记本"))
        self.label_5.setText(_translate("Dialog", "3. \"搜索...\"去百度搜索你的答案"))
